-- Ardent Mills - complete table DDL
-- Extracted from Oracle with DBMS_METADATA. Run top to bottom.
-- Order: sequences -> OLTP (ARD_OPS_*) -> OLAP dims -> OLAP facts -> ETL control

------------------------------------------------------------------------------
-- SEQUENCES (16)
------------------------------------------------------------------------------

CREATE SEQUENCE  "DIM_BIN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 80963 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "DIM_CARRIER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 50503 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "DIM_CLEANING_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 90910 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "DIM_CUSTOMER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 31984 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "DIM_DATE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4129 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "DIM_MAINT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 70746 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "DIM_PACKLINE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 60604 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "DIM_PRODMIX_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100164 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "DIM_PRODUCT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 20615 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "DIM_SHIPTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 40549 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "DIM_SITE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10807 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "FACT_BIN_CLEAN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 506753 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "FACT_MAINT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 505957 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "FACT_MILL_PROD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 503668 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "FACT_PACK_PROD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 502871 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "FACT_SALES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 504053 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

------------------------------------------------------------------------------
-- OLTP TABLES (ARD_OPS_*) (18)
------------------------------------------------------------------------------

CREATE TABLE "ARD_OPS_SITE" 
   (	"SITE_ID" NUMBER(10,0), 
	"SITE_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"OPS_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"REGION" VARCHAR2(50) NOT NULL ENABLE, 
	"PACK_PLANT" VARCHAR2(50) NOT NULL ENABLE, 
	"COMPANY" VARCHAR2(200) NOT NULL ENABLE, 
	"COUNTRY_CD" VARCHAR2(20) NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	 PRIMARY KEY ("SITE_ID")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "ARD_OPS_ITEMCLASS" 
   (	"ITEM_CLASS_ID" NUMBER(30,0) DEFAULT "ITEMCLASS_SEQ"."NEXTVAL", 
	"ITEM_CLASS_DESC" VARCHAR2(200), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	 PRIMARY KEY ("ITEM_CLASS_ID")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "ARD_OPS_PRODUCT" 
   (	"PRODUCT_ID" NUMBER DEFAULT "PRODUCT_SEQ"."NEXTVAL", 
	"PRODUCT_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"PRODUCT_DESC" VARCHAR2(200), 
	"ITEM_CLASS_ID" NUMBER(30,0), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	 PRIMARY KEY ("PRODUCT_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("PRODUCT_CODE")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("ITEM_CLASS_ID")
	  REFERENCES "ARD_OPS_ITEMCLASS" ("ITEM_CLASS_ID") ENABLE
   ) ;
CREATE TABLE "ARD_OPS_CUSTOMER" 
   (	"CUSTOMER_ID" NUMBER(20,0) DEFAULT "CUSTOMER_SEQ"."NEXTVAL", 
	"CUSTOMER_NM" VARCHAR2(100), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	 PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "ARD_OPS_SHIPTOACCOUNT" 
   (	"SHIP_TO_ID" NUMBER(20,0), 
	"SHIP_TO_NAME" VARCHAR2(50), 
	"SOLD_TO_NAME" VARCHAR2(100), 
	"CITY" VARCHAR2(50), 
	"STATE" VARCHAR2(50), 
	"ZIP" VARCHAR2(15), 
	"COUNTRY" VARCHAR2(100), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	 PRIMARY KEY ("SHIP_TO_ID")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "ARD_OPS_CARRIER" 
   (	"CARRIER_ID" NUMBER(20,0) DEFAULT "CARRIER_SEQ"."NEXTVAL", 
	"CARRIER_CODE" VARCHAR2(10) NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	 PRIMARY KEY ("CARRIER_ID")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "ARD_OPS_PRODUCTIONMIX" 
   (	"PRODUCTION_MIX_ID" NUMBER(20,0) DEFAULT "PRODMIX_SEQ"."NEXTVAL", 
	"PRODUCTION_MIX_CODE" VARCHAR2(100) NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	 PRIMARY KEY ("PRODUCTION_MIX_ID")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "ARD_OPS_MAINTENANCETYPE" 
   (	"MAINTENANCE_TYPE_ID" NUMBER(30,0) DEFAULT "MAINTTYPE_SEQ"."NEXTVAL", 
	"MAINTENANCE_TYPE" VARCHAR2(100), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	 PRIMARY KEY ("MAINTENANCE_TYPE_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("MAINTENANCE_TYPE")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "ARD_OPS_CLEANINGTYPE" 
   (	"CLEANING_TYPE_PK" NUMBER DEFAULT "CLEANINGTYPE_SEQ"."NEXTVAL", 
	"CLEANING_TYPE_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"CLEANING_TYPE_DESC" VARCHAR2(200), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(50), 
	 PRIMARY KEY ("CLEANING_TYPE_PK")
  USING INDEX  ENABLE, 
	 UNIQUE ("CLEANING_TYPE_ID")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "ARD_OPS_PACKLINE" 
   (	"LINE_ID" NUMBER(20,0) DEFAULT "PACKLINE_SEQ"."NEXTVAL", 
	"SITE_ID" NUMBER(20,0), 
	"LINE_NAME" VARCHAR2(100), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(50), 
	 PRIMARY KEY ("LINE_ID")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("SITE_ID")
	  REFERENCES "ARD_OPS_SITE" ("SITE_ID") ENABLE
   ) ;
CREATE TABLE "ARD_OPS_BIN" 
   (	"BIN_PK" NUMBER DEFAULT "BIN_SEQ"."NEXTVAL", 
	"BIN_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"BIN_PURPOSE" VARCHAR2(200), 
	"SITE_ID" NUMBER(20,0), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(50), 
	 PRIMARY KEY ("BIN_PK")
  USING INDEX  ENABLE, 
	 UNIQUE ("BIN_ID")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("SITE_ID")
	  REFERENCES "ARD_OPS_SITE" ("SITE_ID") ENABLE
   ) ;
CREATE TABLE "ARD_OPS_PACKRUN" 
   (	"PACK_RUN_ID" NUMBER(20,0) DEFAULT "PACKRUN_SEQ"."NEXTVAL", 
	"SITE_ID" NUMBER(10,0), 
	"PRODUCT_ID" NUMBER, 
	"LINE_ID" NUMBER(20,0), 
	"PACK_DATE" DATE, 
	"GOOD_UNITS" NUMBER, 
	"TARGET_UNITS" NUMBER, 
	"TOTAL_UNITS" NUMBER, 
	"CALC_DT" NUMBER, 
	"MINUTES_RUN" NUMBER, 
	"PACK_OEE" NUMBER, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(50), 
	 PRIMARY KEY ("PACK_RUN_ID")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("SITE_ID")
	  REFERENCES "ARD_OPS_SITE" ("SITE_ID") ENABLE, 
	 FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "ARD_OPS_PRODUCT" ("PRODUCT_ID") ENABLE, 
	 FOREIGN KEY ("LINE_ID")
	  REFERENCES "ARD_OPS_PACKLINE" ("LINE_ID") ENABLE
   ) ;
CREATE TABLE "ARD_OPS_MILLRUN" 
   (	"MILL_RUN_ID" NUMBER DEFAULT "MILLRUN_SEQ"."NEXTVAL", 
	"SITE_ID" NUMBER(10,0), 
	"MILL_DATE" DATE, 
	"UNIT" VARCHAR2(1), 
	"PRODUCTION_MIX_ID" NUMBER(20,0), 
	"CALC_DOWNTIME" NUMBER DEFAULT 0, 
	"MIN_RUN" NUMBER DEFAULT 0, 
	"NO_DEMAND_DOWNTIME" NUMBER DEFAULT 0, 
	"MILL_OEE" NUMBER DEFAULT 0, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(50), 
	 PRIMARY KEY ("MILL_RUN_ID")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("SITE_ID")
	  REFERENCES "ARD_OPS_SITE" ("SITE_ID") ENABLE, 
	 FOREIGN KEY ("PRODUCTION_MIX_ID")
	  REFERENCES "ARD_OPS_PRODUCTIONMIX" ("PRODUCTION_MIX_ID") ENABLE
   ) ;
CREATE TABLE "ARD_OPS_SALESORDER" 
   (	"ORDER_ID" NUMBER DEFAULT "ORDER_SEQ"."NEXTVAL", 
	"ORDER_NO" VARCHAR2(255) NOT NULL ENABLE, 
	"SITE_ID" NUMBER(20,0), 
	"CUSTOMER_ID" NUMBER(20,0), 
	"SHIP_DATE" DATE, 
	"ORDER_STATUS" VARCHAR2(20), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(50), 
	 PRIMARY KEY ("ORDER_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("ORDER_NO")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("SITE_ID")
	  REFERENCES "ARD_OPS_SITE" ("SITE_ID") ENABLE, 
	 FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "ARD_OPS_CUSTOMER" ("CUSTOMER_ID") ENABLE
   ) ;
CREATE TABLE "ARD_OPS_SALESORDERLINE" 
   (	"ORDER_LINE_ID" NUMBER DEFAULT "ORDERLINE_SEQ"."NEXTVAL", 
	"ORDER_NO" VARCHAR2(20), 
	"PRODUCT_ID" NUMBER, 
	"INVOICE_CWTS" NUMBER, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(50), 
	 PRIMARY KEY ("ORDER_LINE_ID")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("ORDER_NO")
	  REFERENCES "ARD_OPS_SALESORDER" ("ORDER_NO") ENABLE, 
	 FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "ARD_OPS_PRODUCT" ("PRODUCT_ID") ENABLE
   ) ;
CREATE TABLE "ARD_OPS_WORKORDER" 
   (	"WORKORDER_ID" NUMBER DEFAULT "WORKORDER_SEQ"."NEXTVAL", 
	"WO_NO" VARCHAR2(20) NOT NULL ENABLE, 
	"SITE_ID" NUMBER(20,0), 
	"MAINTENANCE_TYPE_ID" NUMBER(30,0), 
	"CATEGORY_CD" VARCHAR2(200), 
	"STATUS_CD" VARCHAR2(50), 
	"PREVENTIVE_CORRECTIVE_IND" VARCHAR2(50), 
	"LATE_INDICATOR" VARCHAR2(50), 
	"REQUIRED_DATE" DATE, 
	"WO_COUNT" NUMBER(1,0) DEFAULT 0, 
	"WO_LATE_COUNT" NUMBER(1,0) DEFAULT 0, 
	"WO_ONTIME_COUNT" NUMBER(1,0) DEFAULT 0, 
	"WO_UPCOMING_COUNT" NUMBER(1,0) DEFAULT 0, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(50), 
	 PRIMARY KEY ("WORKORDER_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("WO_NO")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("SITE_ID")
	  REFERENCES "ARD_OPS_SITE" ("SITE_ID") ENABLE, 
	 FOREIGN KEY ("MAINTENANCE_TYPE_ID")
	  REFERENCES "ARD_OPS_MAINTENANCETYPE" ("MAINTENANCE_TYPE_ID") ENABLE
   ) ;
CREATE TABLE "ARD_OPS_BINCLEANINGLOG" 
   (	"CLEANING_LOG_ID" NUMBER DEFAULT "CLEANINGLOG_SEQ"."NEXTVAL", 
	"BIN_ID" VARCHAR2(255), 
	"CLEANING_TYPE_ID" VARCHAR2(255), 
	"CLEANING_COMPLETED_ON" DATE, 
	"CLEANING_COMPLETED_BY" VARCHAR2(20), 
	"DAYS_SINCE_LAST_CLEANING" NUMBER(3,0) DEFAULT 0, 
	"BIN_STATUS" VARCHAR2(20) DEFAULT 'LATE', 
	"CLEAN_STANDARD_IN_PLACE" NUMBER(3,0) DEFAULT 0, 
	"CLEAN_STANDARD_FREQ" NUMBER(3,0) DEFAULT 0, 
	"LAST_REFRESH_TIME" TIMESTAMP (6), 
	"STATUS_AS_OF_DATE" TIMESTAMP (6), 
	"STATUS_AS_OF_WK_START" DATE, 
	"COMMENTS" VARCHAR2(1000), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(50), 
	 PRIMARY KEY ("CLEANING_LOG_ID")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("BIN_ID")
	  REFERENCES "ARD_OPS_BIN" ("BIN_ID") ENABLE, 
	 FOREIGN KEY ("CLEANING_TYPE_ID")
	  REFERENCES "ARD_OPS_CLEANINGTYPE" ("CLEANING_TYPE_ID") ENABLE
   ) ;
CREATE TABLE "ARD_OPS_FILLORDER" 
   (	"FILL_ORDER_ID" NUMBER DEFAULT "FILLORDER_SEQ"."NEXTVAL", 
	"ORDER_NUMBER" NUMBER, 
	"VESSEL_ID" NUMBER, 
	"SITE_ID" NUMBER(20,0), 
	"SHIP_TO_ID" NUMBER(20,0), 
	"CARRIER_ID" NUMBER(20,0), 
	"PRODUCT_ID" NUMBER, 
	"BULK_OR_SACK" VARCHAR2(10), 
	"MILES" NUMBER, 
	"DROP_SHIP" VARCHAR2(1), 
	"MODIFIER" VARCHAR2(3), 
	"DELIVERY_NOTE_NO" NUMBER, 
	"LOAD_DATE" DATE, 
	"SHIP_DATE" DATE, 
	"RELEASED_DATE" DATE, 
	"MONTH_NAME" VARCHAR2(20), 
	"YEAR_MONTH" VARCHAR2(20), 
	"YEAR_WEEK" VARCHAR2(20), 
	"CURRENTWEEK" VARCHAR2(20), 
	"SHIPPED_CWT" NUMBER, 
	"VOLUME" NUMBER, 
	"SITE_GOAL" NUMBER, 
	"SITE_MAX" NUMBER, 
	"EXCEPTION_CWTS" NUMBER, 
	"BASELINE" NUMBER, 
	"MAX_FOR_LOAD" NUMBER, 
	"GOAL_FOR_LOAD" NUMBER, 
	"MADE_GOAL" NUMBER, 
	"VAR_TO_GOAL" NUMBER, 
	"VAR_TO_BASELINE" NUMBER, 
	"VAR_TO_LOAD_MAX" NUMBER, 
	"VAR_TO_SITE_MAX" NUMBER, 
	"EXCLUDED" VARCHAR2(20), 
	"EXCEPTION_FLAG" VARCHAR2(20), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(50), 
	 PRIMARY KEY ("FILL_ORDER_ID")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("SITE_ID")
	  REFERENCES "ARD_OPS_SITE" ("SITE_ID") ENABLE, 
	 FOREIGN KEY ("SHIP_TO_ID")
	  REFERENCES "ARD_OPS_SHIPTOACCOUNT" ("SHIP_TO_ID") ENABLE, 
	 FOREIGN KEY ("CARRIER_ID")
	  REFERENCES "ARD_OPS_CARRIER" ("CARRIER_ID") ENABLE, 
	 FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "ARD_OPS_PRODUCT" ("PRODUCT_ID") ENABLE
   ) ;

------------------------------------------------------------------------------
-- OLAP DIMENSIONS + FACTS (parents before children) (16)
------------------------------------------------------------------------------

CREATE TABLE "DIM_DATE" 
   (	"DATE_KEY" NUMBER DEFAULT "DIM_DATE_SEQ"."NEXTVAL", 
	"FULL_DATE" DATE NOT NULL ENABLE, 
	"DAY" NUMBER, 
	"MONTH" NUMBER, 
	"MONTH_NAME" VARCHAR2(20), 
	"QUARTER" NUMBER, 
	"YEAR" NUMBER, 
	"WEEK" NUMBER, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	 PRIMARY KEY ("DATE_KEY")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "DIM_SITE" 
   (	"SITE_KEY" NUMBER DEFAULT "DIM_SITE_SEQ"."NEXTVAL", 
	"SITE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SITE_NAME" VARCHAR2(20), 
	"OPS_TYPE" VARCHAR2(50), 
	"REGION" VARCHAR2(50), 
	"PACK_PLANT" VARCHAR2(50), 
	"COMPANY" VARCHAR2(200), 
	"COUNTRY_CD" VARCHAR2(20), 
	"EFFECTIVE_START_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"EFFECTIVE_END_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	"ACTIVE_FLAG" CHAR(3) DEFAULT 'YES', 
	 PRIMARY KEY ("SITE_KEY")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "DIM_PRODUCT" 
   (	"PRODUCT_KEY" NUMBER DEFAULT "DIM_PRODUCT_SEQ"."NEXTVAL", 
	"PRODUCT_ID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"PRODUCT_DESC" VARCHAR2(200), 
	"ITEM_CLASS_ID" NUMBER(30,0), 
	"ITEM_CLASS_DESC" VARCHAR2(200), 
	"EFFECTIVE_START_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"EFFECTIVE_END_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	"ACTIVE_FLAG" CHAR(3) DEFAULT 'YES', 
	 PRIMARY KEY ("PRODUCT_KEY")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "DIM_CUSTOMER" 
   (	"CUSTOMER_KEY" NUMBER DEFAULT "DIM_CUSTOMER_SEQ"."NEXTVAL", 
	"CUSTOMER_ID" NUMBER(20,0), 
	"CUSTOMER_NAME" VARCHAR2(150), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	 PRIMARY KEY ("CUSTOMER_KEY")
  USING INDEX  ENABLE, 
	 UNIQUE ("CUSTOMER_ID")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "DIM_SHIPTO" 
   (	"SHIPTO_KEY" NUMBER DEFAULT "DIM_SHIPTO_SEQ"."NEXTVAL", 
	"SHIP_TO_ID" NUMBER(20,0), 
	"SHIP_TO_NAME" VARCHAR2(50), 
	"SOLD_TO_NAME" VARCHAR2(100), 
	"CITY" VARCHAR2(100), 
	"STATE" VARCHAR2(50), 
	"ZIP" VARCHAR2(15), 
	"COUNTRY" VARCHAR2(100), 
	"EFFECTIVE_START_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"EFFECTIVE_END_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	"ACTIVE_FLAG" CHAR(3) DEFAULT 'YES', 
	 PRIMARY KEY ("SHIPTO_KEY")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "DIM_CARRIER" 
   (	"CARRIER_KEY" NUMBER DEFAULT "DIM_CARRIER_SEQ"."NEXTVAL", 
	"CARRIER_ID" NUMBER(20,0), 
	"CARRIER_CODE" VARCHAR2(10), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	 PRIMARY KEY ("CARRIER_KEY")
  USING INDEX  ENABLE, 
	 UNIQUE ("CARRIER_ID")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "DIM_PACKLINE" 
   (	"LINE_KEY" NUMBER DEFAULT "DIM_PACKLINE_SEQ"."NEXTVAL", 
	"LINE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"SITE_ID" NUMBER(10,0), 
	"LINE_NAME" VARCHAR2(100), 
	"SITE_NAME" VARCHAR2(100), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	 PRIMARY KEY ("LINE_KEY")
  USING INDEX  ENABLE, 
	 UNIQUE ("LINE_ID")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "DIM_MAINTENANCE_TYPE" 
   (	"MAINT_KEY" NUMBER DEFAULT "DIM_MAINT_SEQ"."NEXTVAL", 
	"MAINTENANCE_TYPE_ID" NUMBER(30,0), 
	"MAINTENANCE_TYPE" VARCHAR2(100), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	 PRIMARY KEY ("MAINT_KEY")
  USING INDEX  ENABLE, 
	 UNIQUE ("MAINTENANCE_TYPE_ID")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "DIM_BIN" 
   (	"BIN_KEY" NUMBER DEFAULT "DIM_BIN_SEQ"."NEXTVAL", 
	"BIN_PK" NUMBER, 
	"BIN_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"BIN_PURPOSE" VARCHAR2(200), 
	"SITE_ID" NUMBER(10,0), 
	"SITE_NAME" VARCHAR2(100), 
	"EFFECTIVE_START_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"EFFECTIVE_END_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	"ACTIVE_FLAG" CHAR(3) DEFAULT 'YES', 
	 PRIMARY KEY ("BIN_KEY")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "DIM_CLEANING_TYPE" 
   (	"CLEANING_KEY" NUMBER DEFAULT "DIM_CLEANING_SEQ"."NEXTVAL", 
	"CLEANING_TYPE_PK" NUMBER, 
	"CLEANING_TYPE_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"CLEANING_TYPE_DESC" VARCHAR2(200), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	 PRIMARY KEY ("CLEANING_KEY")
  USING INDEX  ENABLE, 
	 UNIQUE ("CLEANING_TYPE_ID")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "DIM_PRODUCTION_MIX" 
   (	"PRODUCTION_MIX_KEY" NUMBER DEFAULT "DIM_PRODMIX_SEQ"."NEXTVAL", 
	"PRODUCTION_MIX_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"PRODUCTION_MIX_CODE" VARCHAR2(100), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	 PRIMARY KEY ("PRODUCTION_MIX_KEY")
  USING INDEX  ENABLE, 
	 UNIQUE ("PRODUCTION_MIX_ID")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "FACT_SALES" 
   (	"SALES_KEY" NUMBER DEFAULT "FACT_SALES_SEQ"."NEXTVAL", 
	"DATE_KEY" NUMBER NOT NULL ENABLE, 
	"SITE_KEY" NUMBER, 
	"PRODUCT_KEY" NUMBER, 
	"SHIPTO_KEY" NUMBER, 
	"CARRIER_KEY" NUMBER, 
	"CUSTOMER_KEY" NUMBER, 
	"SHIPPED_CWT" NUMBER, 
	"VOLUME" NUMBER, 
	"MILES" NUMBER, 
	"SITE_GOAL" NUMBER, 
	"VAR_TO_GOAL" NUMBER, 
	 PRIMARY KEY ("SALES_KEY")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("DATE_KEY")
	  REFERENCES "DIM_DATE" ("DATE_KEY") ENABLE, 
	 FOREIGN KEY ("SITE_KEY")
	  REFERENCES "DIM_SITE" ("SITE_KEY") ENABLE, 
	 FOREIGN KEY ("PRODUCT_KEY")
	  REFERENCES "DIM_PRODUCT" ("PRODUCT_KEY") ENABLE, 
	 FOREIGN KEY ("SHIPTO_KEY")
	  REFERENCES "DIM_SHIPTO" ("SHIPTO_KEY") ENABLE, 
	 FOREIGN KEY ("CARRIER_KEY")
	  REFERENCES "DIM_CARRIER" ("CARRIER_KEY") ENABLE, 
	 FOREIGN KEY ("CUSTOMER_KEY")
	  REFERENCES "DIM_CUSTOMER" ("CUSTOMER_KEY") ENABLE
   ) ;
CREATE TABLE "FACT_PACK_PRODUCTION" 
   (	"PACK_KEY" NUMBER DEFAULT "FACT_PACK_PROD_SEQ"."NEXTVAL", 
	"DATE_KEY" NUMBER NOT NULL ENABLE, 
	"SITE_KEY" NUMBER, 
	"PRODUCT_KEY" NUMBER, 
	"LINE_KEY" NUMBER, 
	"GOOD_UNITS" NUMBER, 
	"TARGET_UNITS" NUMBER, 
	"TOTAL_UNITS" NUMBER, 
	"CALC_DOWNTIME" NUMBER, 
	"MINUTES_RUN" NUMBER, 
	"PACK_OEE" NUMBER, 
	 PRIMARY KEY ("PACK_KEY")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("DATE_KEY")
	  REFERENCES "DIM_DATE" ("DATE_KEY") ENABLE, 
	 FOREIGN KEY ("SITE_KEY")
	  REFERENCES "DIM_SITE" ("SITE_KEY") ENABLE, 
	 FOREIGN KEY ("PRODUCT_KEY")
	  REFERENCES "DIM_PRODUCT" ("PRODUCT_KEY") ENABLE, 
	 FOREIGN KEY ("LINE_KEY")
	  REFERENCES "DIM_PACKLINE" ("LINE_KEY") ENABLE
   ) ;
CREATE TABLE "FACT_MILL_PRODUCTION" 
   (	"MILL_KEY" NUMBER DEFAULT "FACT_MILL_PROD_SEQ"."NEXTVAL", 
	"DATE_KEY" NUMBER NOT NULL ENABLE, 
	"SITE_KEY" NUMBER, 
	"PRODUCTION_MIX_KEY" NUMBER, 
	"UNIT" VARCHAR2(50), 
	"CALC_DOWNTIME" NUMBER, 
	"MIN_RUN" NUMBER, 
	"NO_DEMAND_DOWNTIME" NUMBER, 
	"MILL_OEE" NUMBER, 
	 PRIMARY KEY ("MILL_KEY")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("DATE_KEY")
	  REFERENCES "DIM_DATE" ("DATE_KEY") ENABLE, 
	 FOREIGN KEY ("SITE_KEY")
	  REFERENCES "DIM_SITE" ("SITE_KEY") ENABLE, 
	 FOREIGN KEY ("PRODUCTION_MIX_KEY")
	  REFERENCES "DIM_PRODUCTION_MIX" ("PRODUCTION_MIX_KEY") ENABLE
   ) ;
CREATE TABLE "FACT_MAINTENANCE" 
   (	"MAINT_FACT_KEY" NUMBER DEFAULT "FACT_MAINT_SEQ"."NEXTVAL", 
	"DATE_KEY" NUMBER NOT NULL ENABLE, 
	"SITE_KEY" NUMBER, 
	"MAINT_KEY" NUMBER, 
	"WO_COUNT" NUMBER, 
	"WO_LATE_COUNT" NUMBER, 
	"WO_ONTIME_COUNT" NUMBER, 
	"WO_UPCOMING_COUNT" NUMBER, 
	 PRIMARY KEY ("MAINT_FACT_KEY")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("DATE_KEY")
	  REFERENCES "DIM_DATE" ("DATE_KEY") ENABLE, 
	 FOREIGN KEY ("SITE_KEY")
	  REFERENCES "DIM_SITE" ("SITE_KEY") ENABLE, 
	 FOREIGN KEY ("MAINT_KEY")
	  REFERENCES "DIM_MAINTENANCE_TYPE" ("MAINT_KEY") ENABLE
   ) ;
CREATE TABLE "FACT_BIN_CLEANING" 
   (	"CLEAN_FACT_KEY" NUMBER DEFAULT "FACT_BIN_CLEAN_SEQ"."NEXTVAL", 
	"DATE_KEY" NUMBER, 
	"BIN_KEY" NUMBER, 
	"CLEANING_KEY" NUMBER, 
	"SITE_KEY" NUMBER, 
	"DAYS_SINCE_LAST_CLEANING" NUMBER, 
	"CLEAN_STANDARD_FREQ" NUMBER, 
	 PRIMARY KEY ("CLEAN_FACT_KEY")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("DATE_KEY")
	  REFERENCES "DIM_DATE" ("DATE_KEY") ENABLE, 
	 FOREIGN KEY ("BIN_KEY")
	  REFERENCES "DIM_BIN" ("BIN_KEY") ENABLE, 
	 FOREIGN KEY ("CLEANING_KEY")
	  REFERENCES "DIM_CLEANING_TYPE" ("CLEANING_KEY") ENABLE, 
	 FOREIGN KEY ("SITE_KEY")
	  REFERENCES "DIM_SITE" ("SITE_KEY") ENABLE
   ) ;

------------------------------------------------------------------------------
-- ETL CONTROL / AUDIT TABLES (4)
------------------------------------------------------------------------------

CREATE TABLE "ETL_LOAD_CONTROL" 
   (	"PROCESS_NAME" VARCHAR2(100), 
	"LAST_LOAD_DATE" DATE, 
	"LAST_SUCCESS_DATE" DATE, 
	"STATUS" VARCHAR2(20), 
	 PRIMARY KEY ("PROCESS_NAME")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "ETL_AUDIT" 
   (	"AUDIT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"BATCH_ID" VARCHAR2(32) NOT NULL ENABLE, 
	"PIPELINE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"SOURCE_OBJECT" VARCHAR2(255), 
	"TARGET_TABLE" VARCHAR2(255), 
	"ROWS_READ" NUMBER, 
	"ROWS_LOADED" NUMBER, 
	"ROWS_INSERTED" NUMBER, 
	"ROWS_UPDATED" NUMBER, 
	"ROWS_UNCHANGED" NUMBER, 
	"ROWS_REJECTED" NUMBER, 
	"STATUS" VARCHAR2(10) NOT NULL ENABLE, 
	"ERROR_MESSAGE" VARCHAR2(4000), 
	"STARTED_AT" TIMESTAMP (3) NOT NULL ENABLE, 
	"FINISHED_AT" TIMESTAMP (3), 
	"DURATION_SECONDS" NUMBER(10,2), 
	"EXECUTED_BY" VARCHAR2(128) DEFAULT USER, 
	 CONSTRAINT "CK_ETL_AUDIT_STATUS" CHECK (STATUS IN ('STARTED','SUCCESS','FAILED','SKIPPED')) ENABLE, 
	 CONSTRAINT "PK_ETL_AUDIT" PRIMARY KEY ("AUDIT_ID")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "ETL_ERROR" 
   (	"ERROR_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"BATCH_ID" VARCHAR2(32), 
	"PIPELINE_NAME" VARCHAR2(100), 
	"STAGE" VARCHAR2(100), 
	"TARGET_TABLE" VARCHAR2(255), 
	"RECORD_KEY" VARCHAR2(400), 
	"ERROR_TYPE" VARCHAR2(200), 
	"ERROR_MESSAGE" VARCHAR2(4000), 
	"ERROR_DETAIL" CLOB, 
	"ERROR_TIME" TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "PK_ETL_ERROR" PRIMARY KEY ("ERROR_ID")
  USING INDEX  ENABLE
   ) ;
CREATE TABLE "ETL_FILE_REGISTRY" 
   (	"FILE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(400) NOT NULL ENABLE, 
	"FILE_HASH" VARCHAR2(64) NOT NULL ENABLE, 
	"FILE_SIZE" NUMBER, 
	"ARCHIVE_PATH" VARCHAR2(1000), 
	"STATUS" VARCHAR2(20) NOT NULL ENABLE, 
	"BATCH_ID" VARCHAR2(32), 
	"DISCOVERED_AT" TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"PROCESSED_AT" TIMESTAMP (3), 
	"ERROR_MESSAGE" VARCHAR2(4000), 
	 CONSTRAINT "CK_ETL_FILE_REG_STATUS" CHECK (STATUS IN ('IN_PROGRESS','SUCCESS','FAILED','SKIPPED')) ENABLE, 
	 CONSTRAINT "PK_ETL_FILE_REGISTRY" PRIMARY KEY ("FILE_ID")
  USING INDEX  ENABLE
   ) ;
