-- Ardent Mills - complete procedure DDL
-- Extracted from Oracle USER_SOURCE. Run top to bottom, after 01_tables.sql.
-- Order: leaf INC_LOAD_* procedures first, then the wrappers that call them.

------------------------------------------------------------------------------
-- INCREMENTAL LOAD PROCEDURES (16)
------------------------------------------------------------------------------

-- INC_LOAD_DIM_DATE
CREATE OR REPLACE EDITIONABLE PROCEDURE "INC_LOAD_DIM_DATE" (
    LOAD_DATE IN DATE
) AS
BEGIN
    INSERT INTO DIM_DATE (
        FULL_DATE,
        DAY,
        MONTH,
        MONTH_NAME,
        QUARTER,
        YEAR,
        WEEK,
        CREATED_DATE,
        CREATED_BY
    )
    SELECT
        DT.FULL_DATE,
        EXTRACT(DAY FROM DT.FULL_DATE),
        EXTRACT(MONTH FROM DT.FULL_DATE),
        TRIM(TO_CHAR(DT.FULL_DATE, 'MONTH')),
        TO_NUMBER(TO_CHAR(DT.FULL_DATE, 'Q')),
        EXTRACT(YEAR FROM DT.FULL_DATE),
        TO_NUMBER(TO_CHAR(DT.FULL_DATE, 'IW')),
        SYSDATE,
        USER
    FROM (
        SELECT TRUNC(PACK_DATE) AS FULL_DATE
        FROM ARD_OPS_PACKRUN
        WHERE PACK_DATE IS NOT NULL
        UNION
        SELECT TRUNC(MILL_DATE)
        FROM ARD_OPS_MILLRUN
        WHERE MILL_DATE IS NOT NULL
        UNION
        SELECT TRUNC(SHIP_DATE)
        FROM ARD_OPS_SALESORDER
        WHERE SHIP_DATE IS NOT NULL
        UNION
        SELECT TRUNC(REQUIRED_DATE)
        FROM ARD_OPS_WORKORDER
        WHERE REQUIRED_DATE IS NOT NULL
        UNION
        SELECT TRUNC(CLEANING_COMPLETED_ON)
        FROM ARD_OPS_BINCLEANINGLOG
        WHERE CLEANING_COMPLETED_ON IS NOT NULL
        UNION
        SELECT TRUNC(SHIP_DATE)
        FROM ARD_OPS_FILLORDER
        WHERE SHIP_DATE IS NOT NULL
    ) DT
    WHERE NOT EXISTS (
        SELECT 1
        FROM DIM_DATE D
        WHERE D.FULL_DATE = DT.FULL_DATE
    );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
-- INC_LOAD_DIM_SITE
CREATE OR REPLACE EDITIONABLE PROCEDURE "INC_LOAD_DIM_SITE" (
    LOAD_DATE IN DATE
) AS
BEGIN
    UPDATE DIM_SITE TGT
       SET TGT.ACTIVE_FLAG = 'NO',
           TGT.EFFECTIVE_END_DATE = SYSDATE,
           TGT.UPDATED_BY = USER
     WHERE TGT.ACTIVE_FLAG = 'YES'
       AND EXISTS (
            SELECT 1
            FROM ARD_OPS_SITE SRC
            WHERE SRC.SITE_ID = TGT.SITE_ID
              AND SRC.UPDATED_DATE > LOAD_DATE
              AND (
                    NVL(TGT.SITE_NAME, '#') <> NVL(SRC.SITE_NAME, '#')
                 OR NVL(TGT.OPS_TYPE, '#') <> NVL(SRC.OPS_TYPE, '#')
                 OR NVL(TGT.REGION, '#') <> NVL(SRC.REGION, '#')
                 OR NVL(TGT.PACK_PLANT, '#') <> NVL(SRC.PACK_PLANT, '#')
                 OR NVL(TGT.COMPANY, '#') <> NVL(SRC.COMPANY, '#')
                 OR NVL(TGT.COUNTRY_CD, '#') <> NVL(SRC.COUNTRY_CD, '#')
              )
       );

    INSERT INTO DIM_SITE (
        SITE_ID, SITE_NAME, OPS_TYPE, REGION, PACK_PLANT, COMPANY, COUNTRY_CD,
        EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, CREATED_BY, ACTIVE_FLAG
    )
    SELECT
        SRC.SITE_ID, SRC.SITE_NAME, SRC.OPS_TYPE, SRC.REGION, SRC.PACK_PLANT,
        SRC.COMPANY, SRC.COUNTRY_CD, SYSDATE, NULL, USER, 'YES'
    FROM ARD_OPS_SITE SRC
    WHERE (SRC.CREATED_DATE > LOAD_DATE
           OR NVL(SRC.UPDATED_DATE, SRC.CREATED_DATE) > LOAD_DATE)
      AND NOT EXISTS (
            SELECT 1
            FROM DIM_SITE TGT
            WHERE TGT.SITE_ID = SRC.SITE_ID
              AND TGT.ACTIVE_FLAG = 'YES'
              AND NVL(TGT.SITE_NAME, '#') = NVL(SRC.SITE_NAME, '#')
              AND NVL(TGT.OPS_TYPE, '#') = NVL(SRC.OPS_TYPE, '#')
              AND NVL(TGT.REGION, '#') = NVL(SRC.REGION, '#')
              AND NVL(TGT.PACK_PLANT, '#') = NVL(SRC.PACK_PLANT, '#')
              AND NVL(TGT.COMPANY, '#') = NVL(SRC.COMPANY, '#')
              AND NVL(TGT.COUNTRY_CD, '#') = NVL(SRC.COUNTRY_CD, '#')
      );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
-- INC_LOAD_DIM_PRODUCT
CREATE OR REPLACE EDITIONABLE PROCEDURE "INC_LOAD_DIM_PRODUCT" (
    LOAD_DATE IN DATE
) AS
BEGIN
    UPDATE DIM_PRODUCT TGT
       SET TGT.ACTIVE_FLAG = 'NO',
           TGT.EFFECTIVE_END_DATE = SYSDATE,
           TGT.UPDATED_BY = USER
     WHERE TGT.ACTIVE_FLAG = 'YES'
       AND EXISTS (
            SELECT 1
            FROM ARD_OPS_PRODUCT P
            LEFT JOIN ARD_OPS_ITEMCLASS IC
                ON IC.ITEM_CLASS_ID = P.ITEM_CLASS_ID
            WHERE P.PRODUCT_ID = TGT.PRODUCT_ID
              AND P.UPDATED_DATE > LOAD_DATE
              AND (
                    NVL(TGT.PRODUCT_CODE, '#') <> NVL(P.PRODUCT_CODE, '#')
                 OR NVL(TGT.PRODUCT_DESC, '#') <> NVL(P.PRODUCT_DESC, '#')
                 OR NVL(TGT.ITEM_CLASS_ID, -1) <> NVL(P.ITEM_CLASS_ID, -1)
                 OR NVL(TGT.ITEM_CLASS_DESC, '#') <> NVL(IC.ITEM_CLASS_DESC, '#')
              )
       );

    INSERT INTO DIM_PRODUCT (
        PRODUCT_ID, PRODUCT_CODE, PRODUCT_DESC, ITEM_CLASS_ID, ITEM_CLASS_DESC,
        EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, CREATED_BY, ACTIVE_FLAG
    )
    SELECT
        P.PRODUCT_ID, P.PRODUCT_CODE, P.PRODUCT_DESC, P.ITEM_CLASS_ID,
        IC.ITEM_CLASS_DESC, SYSDATE, NULL, USER, 'YES'
    FROM ARD_OPS_PRODUCT P
    LEFT JOIN ARD_OPS_ITEMCLASS IC
        ON IC.ITEM_CLASS_ID = P.ITEM_CLASS_ID
    WHERE (P.CREATED_DATE > LOAD_DATE
           OR NVL(P.UPDATED_DATE, P.CREATED_DATE) > LOAD_DATE)
      AND NOT EXISTS (
            SELECT 1
            FROM DIM_PRODUCT TGT
            WHERE TGT.PRODUCT_ID = P.PRODUCT_ID
              AND TGT.ACTIVE_FLAG = 'YES'
              AND NVL(TGT.PRODUCT_CODE, '#') = NVL(P.PRODUCT_CODE, '#')
              AND NVL(TGT.PRODUCT_DESC, '#') = NVL(P.PRODUCT_DESC, '#')
              AND NVL(TGT.ITEM_CLASS_ID, -1) = NVL(P.ITEM_CLASS_ID, -1)
              AND NVL(TGT.ITEM_CLASS_DESC, '#') = NVL(IC.ITEM_CLASS_DESC, '#')
      );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
-- INC_LOAD_DIM_CUSTOMER
CREATE OR REPLACE EDITIONABLE PROCEDURE "INC_LOAD_DIM_CUSTOMER" (
    LOAD_DATE IN DATE
) AS
BEGIN
    MERGE INTO DIM_CUSTOMER TGT
    USING (
        SELECT CUSTOMER_ID, CUSTOMER_NM AS CUSTOMER_NAME
        FROM ARD_OPS_CUSTOMER
        WHERE CREATED_DATE > LOAD_DATE
           OR NVL(UPDATED_DATE, CREATED_DATE) > LOAD_DATE
    ) SRC
    ON (TGT.CUSTOMER_ID = SRC.CUSTOMER_ID)
    WHEN MATCHED THEN
        UPDATE SET
            TGT.CUSTOMER_NAME = SRC.CUSTOMER_NAME,
            TGT.UPDATED_DATE = SYSDATE,
            TGT.UPDATED_BY = USER
        WHERE NVL(TGT.CUSTOMER_NAME, '#') <> NVL(SRC.CUSTOMER_NAME, '#')
    WHEN NOT MATCHED THEN
        INSERT (CUSTOMER_ID, CUSTOMER_NAME, CREATED_DATE, CREATED_BY)
        VALUES (SRC.CUSTOMER_ID, SRC.CUSTOMER_NAME, SYSDATE, USER);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
-- INC_LOAD_DIM_SHIPTO
CREATE OR REPLACE EDITIONABLE PROCEDURE "INC_LOAD_DIM_SHIPTO" (
    LOAD_DATE IN DATE
) AS
BEGIN
    UPDATE DIM_SHIPTO TGT
       SET TGT.ACTIVE_FLAG = 'NO',
           TGT.EFFECTIVE_END_DATE = SYSDATE,
           TGT.UPDATED_BY = USER
     WHERE TGT.ACTIVE_FLAG = 'YES'
       AND EXISTS (
            SELECT 1
            FROM ARD_OPS_SHIPTOACCOUNT SRC
            WHERE SRC.SHIP_TO_ID = TGT.SHIP_TO_ID
              AND SRC.UPDATED_DATE > LOAD_DATE
              AND (
                    NVL(TGT.SHIP_TO_NAME, '#') <> NVL(SRC.SHIP_TO_NAME, '#')
                 OR NVL(TGT.SOLD_TO_NAME, '#') <> NVL(SRC.SOLD_TO_NAME, '#')
                 OR NVL(TGT.CITY, '#') <> NVL(SRC.CITY, '#')
                 OR NVL(TGT.STATE, '#') <> NVL(SRC.STATE, '#')
                 OR NVL(TGT.ZIP, '#') <> NVL(SRC.ZIP, '#')
                 OR NVL(TGT.COUNTRY, '#') <> NVL(SRC.COUNTRY, '#')
              )
       );

    INSERT INTO DIM_SHIPTO (
        SHIP_TO_ID, SHIP_TO_NAME, SOLD_TO_NAME, CITY, STATE, ZIP, COUNTRY,
        EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, CREATED_BY, ACTIVE_FLAG
    )
    SELECT
        SRC.SHIP_TO_ID, SRC.SHIP_TO_NAME, SRC.SOLD_TO_NAME, SRC.CITY,
        SRC.STATE, SRC.ZIP, SRC.COUNTRY, SYSDATE, NULL, USER, 'YES'
    FROM ARD_OPS_SHIPTOACCOUNT SRC
    WHERE (SRC.CREATED_DATE > LOAD_DATE
           OR NVL(SRC.UPDATED_DATE, SRC.CREATED_DATE) > LOAD_DATE)
      AND NOT EXISTS (
            SELECT 1
            FROM DIM_SHIPTO TGT
            WHERE TGT.SHIP_TO_ID = SRC.SHIP_TO_ID
              AND TGT.ACTIVE_FLAG = 'YES'
              AND NVL(TGT.SHIP_TO_NAME, '#') = NVL(SRC.SHIP_TO_NAME, '#')
              AND NVL(TGT.SOLD_TO_NAME, '#') = NVL(SRC.SOLD_TO_NAME, '#')
              AND NVL(TGT.CITY, '#') = NVL(SRC.CITY, '#')
              AND NVL(TGT.STATE, '#') = NVL(SRC.STATE, '#')
              AND NVL(TGT.ZIP, '#') = NVL(SRC.ZIP, '#')
              AND NVL(TGT.COUNTRY, '#') = NVL(SRC.COUNTRY, '#')
      );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
-- INC_LOAD_DIM_CARRIER
CREATE OR REPLACE EDITIONABLE PROCEDURE "INC_LOAD_DIM_CARRIER" (
    LOAD_DATE IN DATE
) AS
BEGIN
    MERGE INTO DIM_CARRIER TGT
    USING (
        SELECT CARRIER_ID, CARRIER_CODE
        FROM ARD_OPS_CARRIER
        WHERE CREATED_DATE > LOAD_DATE
           OR NVL(UPDATED_DATE, CREATED_DATE) > LOAD_DATE
    ) SRC
    ON (TGT.CARRIER_ID = SRC.CARRIER_ID)
    WHEN MATCHED THEN
        UPDATE SET
            TGT.CARRIER_CODE = SRC.CARRIER_CODE,
            TGT.UPDATED_DATE = SYSDATE,
            TGT.UPDATED_BY = USER
        WHERE NVL(TGT.CARRIER_CODE, '#') <> NVL(SRC.CARRIER_CODE, '#')
    WHEN NOT MATCHED THEN
        INSERT (CARRIER_ID, CARRIER_CODE, CREATED_DATE, CREATED_BY)
        VALUES (SRC.CARRIER_ID, SRC.CARRIER_CODE, SYSDATE, USER);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
-- INC_LOAD_DIM_PACKLINE
CREATE OR REPLACE EDITIONABLE PROCEDURE "INC_LOAD_DIM_PACKLINE" (
    LOAD_DATE IN DATE
) AS
BEGIN
    MERGE INTO DIM_PACKLINE TGT
    USING (
        SELECT
            L.LINE_ID,
            L.SITE_ID,
            L.LINE_NAME,
            S.SITE_NAME
        FROM ARD_OPS_PACKLINE L
        LEFT JOIN ARD_OPS_SITE S
            ON S.SITE_ID = L.SITE_ID
        WHERE L.CREATED_DATE > LOAD_DATE
           OR NVL(L.UPDATED_DATE, L.CREATED_DATE) > LOAD_DATE
    ) SRC
    ON (TGT.LINE_ID = SRC.LINE_ID)
    WHEN MATCHED THEN
        UPDATE SET
            TGT.SITE_ID = SRC.SITE_ID,
            TGT.LINE_NAME = SRC.LINE_NAME,
            TGT.SITE_NAME = SRC.SITE_NAME,
            TGT.UPDATED_DATE = SYSDATE,
            TGT.UPDATED_BY = USER
        WHERE NVL(TGT.SITE_ID, -1) <> NVL(SRC.SITE_ID, -1)
           OR NVL(TGT.LINE_NAME, '#') <> NVL(SRC.LINE_NAME, '#')
           OR NVL(TGT.SITE_NAME, '#') <> NVL(SRC.SITE_NAME, '#')
    WHEN NOT MATCHED THEN
        INSERT (LINE_ID, SITE_ID, LINE_NAME, SITE_NAME, CREATED_DATE, CREATED_BY)
        VALUES (SRC.LINE_ID, SRC.SITE_ID, SRC.LINE_NAME, SRC.SITE_NAME, SYSDATE, USER);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
-- INC_LOAD_DIM_MAINTENANCE_TYPE
CREATE OR REPLACE EDITIONABLE PROCEDURE "INC_LOAD_DIM_MAINTENANCE_TYPE" (
    LOAD_DATE IN DATE
) AS
BEGIN
    MERGE INTO DIM_MAINTENANCE_TYPE TGT
    USING (
        SELECT MAINTENANCE_TYPE_ID, MAINTENANCE_TYPE
        FROM ARD_OPS_MAINTENANCETYPE
        WHERE CREATED_DATE > LOAD_DATE
           OR NVL(UPDATED_DATE, CREATED_DATE) > LOAD_DATE
    ) SRC
    ON (TGT.MAINTENANCE_TYPE_ID = SRC.MAINTENANCE_TYPE_ID)
    WHEN MATCHED THEN
        UPDATE SET
            TGT.MAINTENANCE_TYPE = SRC.MAINTENANCE_TYPE,
            TGT.UPDATED_DATE = SYSDATE,
            TGT.UPDATED_BY = USER
        WHERE NVL(TGT.MAINTENANCE_TYPE, '#') <> NVL(SRC.MAINTENANCE_TYPE, '#')
    WHEN NOT MATCHED THEN
        INSERT (MAINTENANCE_TYPE_ID, MAINTENANCE_TYPE, CREATED_DATE, CREATED_BY)
        VALUES (SRC.MAINTENANCE_TYPE_ID, SRC.MAINTENANCE_TYPE, SYSDATE, USER);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
-- INC_LOAD_DIM_BIN
CREATE OR REPLACE EDITIONABLE PROCEDURE "INC_LOAD_DIM_BIN" (
    LOAD_DATE IN DATE
) AS
BEGIN
    UPDATE DIM_BIN TGT
       SET TGT.ACTIVE_FLAG = 'NO',
           TGT.EFFECTIVE_END_DATE = SYSDATE,
           TGT.UPDATED_BY = USER
     WHERE TGT.ACTIVE_FLAG = 'YES'
       AND EXISTS (
            SELECT 1
            FROM ARD_OPS_BIN B
            LEFT JOIN ARD_OPS_SITE S
                ON S.SITE_ID = B.SITE_ID
            WHERE B.BIN_ID = TGT.BIN_ID
              AND B.UPDATED_DATE > LOAD_DATE
              AND (
                    NVL(TGT.BIN_PK, -1) <> NVL(B.BIN_PK, -1)
                 OR NVL(TGT.BIN_PURPOSE, '#') <> NVL(B.BIN_PURPOSE, '#')
                 OR NVL(TGT.SITE_ID, -1) <> NVL(B.SITE_ID, -1)
                 OR NVL(TGT.SITE_NAME, '#') <> NVL(S.SITE_NAME, '#')
              )
       );

    INSERT INTO DIM_BIN (
        BIN_PK, BIN_ID, BIN_PURPOSE, SITE_ID, SITE_NAME,
        EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, CREATED_BY, ACTIVE_FLAG
    )
    SELECT
        B.BIN_PK, B.BIN_ID, B.BIN_PURPOSE, B.SITE_ID, S.SITE_NAME,
        SYSDATE, NULL, USER, 'YES'
    FROM ARD_OPS_BIN B
    LEFT JOIN ARD_OPS_SITE S
        ON S.SITE_ID = B.SITE_ID
    WHERE (B.CREATED_DATE > LOAD_DATE
           OR NVL(B.UPDATED_DATE, B.CREATED_DATE) > LOAD_DATE)
      AND NOT EXISTS (
            SELECT 1
            FROM DIM_BIN TGT
            WHERE TGT.BIN_ID = B.BIN_ID
              AND TGT.ACTIVE_FLAG = 'YES'
              AND NVL(TGT.BIN_PK, -1) = NVL(B.BIN_PK, -1)
              AND NVL(TGT.BIN_PURPOSE, '#') = NVL(B.BIN_PURPOSE, '#')
              AND NVL(TGT.SITE_ID, -1) = NVL(B.SITE_ID, -1)
              AND NVL(TGT.SITE_NAME, '#') = NVL(S.SITE_NAME, '#')
      );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
-- INC_LOAD_DIM_CLEANING_TYPE
CREATE OR REPLACE EDITIONABLE PROCEDURE "INC_LOAD_DIM_CLEANING_TYPE" (
    LOAD_DATE IN DATE
) AS
BEGIN
    MERGE INTO DIM_CLEANING_TYPE TGT
    USING (
        SELECT CLEANING_TYPE_PK, CLEANING_TYPE_ID, CLEANING_TYPE_DESC
        FROM ARD_OPS_CLEANINGTYPE
        WHERE CREATED_DATE > LOAD_DATE
           OR NVL(UPDATED_DATE, CREATED_DATE) > LOAD_DATE
    ) SRC
    ON (TGT.CLEANING_TYPE_ID = SRC.CLEANING_TYPE_ID)
    WHEN MATCHED THEN
        UPDATE SET
            TGT.CLEANING_TYPE_PK = SRC.CLEANING_TYPE_PK,
            TGT.CLEANING_TYPE_DESC = SRC.CLEANING_TYPE_DESC,
            TGT.UPDATED_DATE = SYSDATE,
            TGT.UPDATED_BY = USER
        WHERE NVL(TGT.CLEANING_TYPE_PK, -1) <> NVL(SRC.CLEANING_TYPE_PK, -1)
           OR NVL(TGT.CLEANING_TYPE_DESC, '#') <> NVL(SRC.CLEANING_TYPE_DESC, '#')
    WHEN NOT MATCHED THEN
        INSERT (
            CLEANING_TYPE_PK, CLEANING_TYPE_ID, CLEANING_TYPE_DESC,
            CREATED_DATE, CREATED_BY
        )
        VALUES (
            SRC.CLEANING_TYPE_PK, SRC.CLEANING_TYPE_ID, SRC.CLEANING_TYPE_DESC,
            SYSDATE, USER
        );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
-- INC_LOAD_DIM_PRODUCTION_MIX
CREATE OR REPLACE EDITIONABLE PROCEDURE "INC_LOAD_DIM_PRODUCTION_MIX" (
    LOAD_DATE IN DATE
) AS
BEGIN
    MERGE INTO DIM_PRODUCTION_MIX TGT
    USING (
        SELECT PRODUCTION_MIX_ID, PRODUCTION_MIX_CODE
        FROM ARD_OPS_PRODUCTIONMIX
        WHERE CREATED_DATE > LOAD_DATE
           OR NVL(UPDATED_DATE, CREATED_DATE) > LOAD_DATE
    ) SRC
    ON (TGT.PRODUCTION_MIX_ID = SRC.PRODUCTION_MIX_ID)
    WHEN MATCHED THEN
        UPDATE SET
            TGT.PRODUCTION_MIX_CODE = SRC.PRODUCTION_MIX_CODE,
            TGT.UPDATED_DATE = SYSDATE,
            TGT.UPDATED_BY = USER
        WHERE NVL(TGT.PRODUCTION_MIX_CODE, '#') <> NVL(SRC.PRODUCTION_MIX_CODE, '#')
    WHEN NOT MATCHED THEN
        INSERT (PRODUCTION_MIX_ID, PRODUCTION_MIX_CODE, CREATED_DATE, CREATED_BY)
        VALUES (SRC.PRODUCTION_MIX_ID, SRC.PRODUCTION_MIX_CODE, SYSDATE, USER);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
-- INC_LOAD_FACT_SALES
CREATE OR REPLACE EDITIONABLE PROCEDURE "INC_LOAD_FACT_SALES" (
    LOAD_DATE IN DATE
) AS
BEGIN
    MERGE INTO FACT_SALES TGT
    USING (
        SELECT
            DATE_KEY,
            SITE_KEY,
            PRODUCT_KEY,
            SHIPTO_KEY,
            CARRIER_KEY,
            CUSTOMER_KEY,
            SUM(SHIPPED_CWT) AS SHIPPED_CWT,
            SUM(VOLUME) AS VOLUME,
            SUM(MILES) AS MILES,
            SUM(SITE_GOAL) AS SITE_GOAL,
            SUM(VAR_TO_GOAL) AS VAR_TO_GOAL
        FROM (
            SELECT
                D.DATE_KEY,
                DS.SITE_KEY,
                DP.PRODUCT_KEY,
                DST.SHIPTO_KEY,
                DCAR.CARRIER_KEY,
                DCUST.CUSTOMER_KEY,
                F.SHIPPED_CWT,
                F.VOLUME,
                F.MILES,
                F.SITE_GOAL,
                F.VAR_TO_GOAL
            FROM ARD_OPS_FILLORDER F
            LEFT JOIN ARD_OPS_SALESORDER SO
                ON SO.ORDER_NO = TO_CHAR(F.ORDER_NUMBER)
            LEFT JOIN DIM_CUSTOMER DCUST
                ON DCUST.CUSTOMER_ID = SO.CUSTOMER_ID
            JOIN DIM_DATE D
                ON D.FULL_DATE = TRUNC(F.SHIP_DATE)
            LEFT JOIN DIM_SITE DS
                ON DS.SITE_ID = F.SITE_ID
               AND DS.ACTIVE_FLAG = 'YES'
            LEFT JOIN DIM_PRODUCT DP
                ON DP.PRODUCT_ID = F.PRODUCT_ID
               AND DP.ACTIVE_FLAG = 'YES'
            LEFT JOIN DIM_SHIPTO DST
                ON DST.SHIP_TO_ID = F.SHIP_TO_ID
               AND DST.ACTIVE_FLAG = 'YES'
            LEFT JOIN DIM_CARRIER DCAR
                ON DCAR.CARRIER_ID = F.CARRIER_ID
            WHERE F.SHIP_DATE IS NOT NULL
              AND (F.CREATED_DATE > LOAD_DATE
                   OR NVL(F.UPDATED_DATE, F.CREATED_DATE) > LOAD_DATE)
        )
        GROUP BY
            DATE_KEY,
            SITE_KEY,
            PRODUCT_KEY,
            SHIPTO_KEY,
            CARRIER_KEY,
            CUSTOMER_KEY
    ) SRC
    ON (
        TGT.DATE_KEY = SRC.DATE_KEY
        AND NVL(TGT.SITE_KEY, -1) = NVL(SRC.SITE_KEY, -1)
        AND NVL(TGT.PRODUCT_KEY, -1) = NVL(SRC.PRODUCT_KEY, -1)
        AND NVL(TGT.SHIPTO_KEY, -1) = NVL(SRC.SHIPTO_KEY, -1)
        AND NVL(TGT.CARRIER_KEY, -1) = NVL(SRC.CARRIER_KEY, -1)
        AND NVL(TGT.CUSTOMER_KEY, -1) = NVL(SRC.CUSTOMER_KEY, -1)
    )
    WHEN MATCHED THEN
        UPDATE SET
            TGT.SHIPPED_CWT = SRC.SHIPPED_CWT,
            TGT.VOLUME = SRC.VOLUME,
            TGT.MILES = SRC.MILES,
            TGT.SITE_GOAL = SRC.SITE_GOAL,
            TGT.VAR_TO_GOAL = SRC.VAR_TO_GOAL
    WHEN NOT MATCHED THEN
        INSERT (
            DATE_KEY, SITE_KEY, PRODUCT_KEY, SHIPTO_KEY, CARRIER_KEY,
            CUSTOMER_KEY, SHIPPED_CWT, VOLUME, MILES, SITE_GOAL, VAR_TO_GOAL
        )
        VALUES (
            SRC.DATE_KEY, SRC.SITE_KEY, SRC.PRODUCT_KEY, SRC.SHIPTO_KEY,
            SRC.CARRIER_KEY, SRC.CUSTOMER_KEY, SRC.SHIPPED_CWT, SRC.VOLUME,
            SRC.MILES, SRC.SITE_GOAL, SRC.VAR_TO_GOAL
        );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
-- INC_LOAD_FACT_PACK_PRODUCTION
CREATE OR REPLACE EDITIONABLE PROCEDURE "INC_LOAD_FACT_PACK_PRODUCTION" (
    LOAD_DATE IN DATE
) AS
BEGIN
    MERGE INTO FACT_PACK_PRODUCTION TGT
    USING (
        SELECT
            D.DATE_KEY,
            DS.SITE_KEY,
            DP.PRODUCT_KEY,
            DL.LINE_KEY,
            SUM(P.GOOD_UNITS) AS GOOD_UNITS,
            SUM(P.TARGET_UNITS) AS TARGET_UNITS,
            SUM(P.TOTAL_UNITS) AS TOTAL_UNITS,
            SUM(P.CALC_DT) AS CALC_DOWNTIME,
            SUM(P.MINUTES_RUN) AS MINUTES_RUN,
            AVG(P.PACK_OEE) AS PACK_OEE
        FROM ARD_OPS_PACKRUN P
        JOIN DIM_DATE D
            ON D.FULL_DATE = TRUNC(P.PACK_DATE)
        LEFT JOIN DIM_SITE DS
            ON DS.SITE_ID = P.SITE_ID
           AND DS.ACTIVE_FLAG = 'YES'
        LEFT JOIN DIM_PRODUCT DP
            ON DP.PRODUCT_ID = P.PRODUCT_ID
           AND DP.ACTIVE_FLAG = 'YES'
        LEFT JOIN DIM_PACKLINE DL
            ON DL.LINE_ID = P.LINE_ID
        WHERE P.PACK_DATE IS NOT NULL
          AND (P.CREATED_DATE > LOAD_DATE
               OR NVL(P.UPDATED_DATE, P.CREATED_DATE) > LOAD_DATE)
        GROUP BY
            D.DATE_KEY,
            DS.SITE_KEY,
            DP.PRODUCT_KEY,
            DL.LINE_KEY
    ) SRC
    ON (
        TGT.DATE_KEY = SRC.DATE_KEY
        AND NVL(TGT.SITE_KEY, -1) = NVL(SRC.SITE_KEY, -1)
        AND NVL(TGT.PRODUCT_KEY, -1) = NVL(SRC.PRODUCT_KEY, -1)
        AND NVL(TGT.LINE_KEY, -1) = NVL(SRC.LINE_KEY, -1)
    )
    WHEN MATCHED THEN
        UPDATE SET
            TGT.GOOD_UNITS = SRC.GOOD_UNITS,
            TGT.TARGET_UNITS = SRC.TARGET_UNITS,
            TGT.TOTAL_UNITS = SRC.TOTAL_UNITS,
            TGT.CALC_DOWNTIME = SRC.CALC_DOWNTIME,
            TGT.MINUTES_RUN = SRC.MINUTES_RUN,
            TGT.PACK_OEE = SRC.PACK_OEE
    WHEN NOT MATCHED THEN
        INSERT (
            DATE_KEY, SITE_KEY, PRODUCT_KEY, LINE_KEY, GOOD_UNITS,
            TARGET_UNITS, TOTAL_UNITS, CALC_DOWNTIME, MINUTES_RUN, PACK_OEE
        )
        VALUES (
            SRC.DATE_KEY, SRC.SITE_KEY, SRC.PRODUCT_KEY, SRC.LINE_KEY,
            SRC.GOOD_UNITS, SRC.TARGET_UNITS, SRC.TOTAL_UNITS,
            SRC.CALC_DOWNTIME, SRC.MINUTES_RUN, SRC.PACK_OEE
        );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
-- INC_LOAD_FACT_MILL_PRODUCTION
CREATE OR REPLACE EDITIONABLE PROCEDURE "INC_LOAD_FACT_MILL_PRODUCTION" (
    LOAD_DATE IN DATE
) AS
BEGIN
    MERGE INTO FACT_MILL_PRODUCTION TGT
    USING (
        SELECT
            D.DATE_KEY,
            DS.SITE_KEY,
            DPM.PRODUCTION_MIX_KEY,
            M.UNIT,
            SUM(M.CALC_DOWNTIME) AS CALC_DOWNTIME,
            SUM(M.MIN_RUN) AS MIN_RUN,
            SUM(M.NO_DEMAND_DOWNTIME) AS NO_DEMAND_DOWNTIME,
            AVG(M.MILL_OEE) AS MILL_OEE
        FROM ARD_OPS_MILLRUN M
        JOIN DIM_DATE D
            ON D.FULL_DATE = TRUNC(M.MILL_DATE)
        LEFT JOIN DIM_SITE DS
            ON DS.SITE_ID = M.SITE_ID
           AND DS.ACTIVE_FLAG = 'YES'
        LEFT JOIN DIM_PRODUCTION_MIX DPM
            ON DPM.PRODUCTION_MIX_ID = M.PRODUCTION_MIX_ID
        WHERE M.MILL_DATE IS NOT NULL
          AND (M.CREATED_DATE > LOAD_DATE
               OR NVL(M.UPDATED_DATE, M.CREATED_DATE) > LOAD_DATE)
        GROUP BY
            D.DATE_KEY,
            DS.SITE_KEY,
            DPM.PRODUCTION_MIX_KEY,
            M.UNIT
    ) SRC
    ON (
        TGT.DATE_KEY = SRC.DATE_KEY
        AND NVL(TGT.SITE_KEY, -1) = NVL(SRC.SITE_KEY, -1)
        AND NVL(TGT.PRODUCTION_MIX_KEY, -1) = NVL(SRC.PRODUCTION_MIX_KEY, -1)
        AND NVL(TGT.UNIT, '#') = NVL(SRC.UNIT, '#')
    )
    WHEN MATCHED THEN
        UPDATE SET
            TGT.CALC_DOWNTIME = SRC.CALC_DOWNTIME,
            TGT.MIN_RUN = SRC.MIN_RUN,
            TGT.NO_DEMAND_DOWNTIME = SRC.NO_DEMAND_DOWNTIME,
            TGT.MILL_OEE = SRC.MILL_OEE
    WHEN NOT MATCHED THEN
        INSERT (
            DATE_KEY, SITE_KEY, PRODUCTION_MIX_KEY, UNIT, CALC_DOWNTIME,
            MIN_RUN, NO_DEMAND_DOWNTIME, MILL_OEE
        )
        VALUES (
            SRC.DATE_KEY, SRC.SITE_KEY, SRC.PRODUCTION_MIX_KEY, SRC.UNIT,
            SRC.CALC_DOWNTIME, SRC.MIN_RUN, SRC.NO_DEMAND_DOWNTIME,
            SRC.MILL_OEE
        );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
-- INC_LOAD_FACT_MAINTENANCE
CREATE OR REPLACE EDITIONABLE PROCEDURE "INC_LOAD_FACT_MAINTENANCE" (
    LOAD_DATE IN DATE
) AS
BEGIN
    MERGE INTO FACT_MAINTENANCE TGT
    USING (
        SELECT
            D.DATE_KEY,
            DS.SITE_KEY,
            DMT.MAINT_KEY,
            SUM(W.WO_COUNT) AS WO_COUNT,
            SUM(W.WO_LATE_COUNT) AS WO_LATE_COUNT,
            SUM(W.WO_ONTIME_COUNT) AS WO_ONTIME_COUNT,
            SUM(W.WO_UPCOMING_COUNT) AS WO_UPCOMING_COUNT
        FROM ARD_OPS_WORKORDER W
        JOIN DIM_DATE D
            ON D.FULL_DATE = TRUNC(W.REQUIRED_DATE)
        LEFT JOIN DIM_SITE DS
            ON DS.SITE_ID = W.SITE_ID
           AND DS.ACTIVE_FLAG = 'YES'
        LEFT JOIN DIM_MAINTENANCE_TYPE DMT
            ON DMT.MAINTENANCE_TYPE_ID = W.MAINTENANCE_TYPE_ID
        WHERE W.REQUIRED_DATE IS NOT NULL
          AND (W.CREATED_DATE > LOAD_DATE
               OR NVL(W.UPDATED_DATE, W.CREATED_DATE) > LOAD_DATE)
        GROUP BY
            D.DATE_KEY,
            DS.SITE_KEY,
            DMT.MAINT_KEY
    ) SRC
    ON (
        TGT.DATE_KEY = SRC.DATE_KEY
        AND NVL(TGT.SITE_KEY, -1) = NVL(SRC.SITE_KEY, -1)
        AND NVL(TGT.MAINT_KEY, -1) = NVL(SRC.MAINT_KEY, -1)
    )
    WHEN MATCHED THEN
        UPDATE SET
            TGT.WO_COUNT = SRC.WO_COUNT,
            TGT.WO_LATE_COUNT = SRC.WO_LATE_COUNT,
            TGT.WO_ONTIME_COUNT = SRC.WO_ONTIME_COUNT,
            TGT.WO_UPCOMING_COUNT = SRC.WO_UPCOMING_COUNT
    WHEN NOT MATCHED THEN
        INSERT (
            DATE_KEY, SITE_KEY, MAINT_KEY, WO_COUNT, WO_LATE_COUNT,
            WO_ONTIME_COUNT, WO_UPCOMING_COUNT
        )
        VALUES (
            SRC.DATE_KEY, SRC.SITE_KEY, SRC.MAINT_KEY, SRC.WO_COUNT,
            SRC.WO_LATE_COUNT, SRC.WO_ONTIME_COUNT, SRC.WO_UPCOMING_COUNT
        );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
-- INC_LOAD_FACT_BIN_CLEANING
CREATE OR REPLACE EDITIONABLE PROCEDURE "INC_LOAD_FACT_BIN_CLEANING" (
    LOAD_DATE IN DATE
) AS
BEGIN
    MERGE INTO FACT_BIN_CLEANING TGT
    USING (
        SELECT
            D.DATE_KEY,
            DB.BIN_KEY,
            DCT.CLEANING_KEY,
            DS.SITE_KEY,
            MAX(BCL.DAYS_SINCE_LAST_CLEANING) AS DAYS_SINCE_LAST_CLEANING,
            MAX(BCL.CLEAN_STANDARD_FREQ) AS CLEAN_STANDARD_FREQ
        FROM ARD_OPS_BINCLEANINGLOG BCL
        JOIN DIM_DATE D
            ON D.FULL_DATE = TRUNC(BCL.CLEANING_COMPLETED_ON)
        LEFT JOIN DIM_BIN DB
            ON DB.BIN_ID = BCL.BIN_ID
           AND DB.ACTIVE_FLAG = 'YES'
        LEFT JOIN DIM_CLEANING_TYPE DCT
            ON DCT.CLEANING_TYPE_ID = BCL.CLEANING_TYPE_ID
        LEFT JOIN DIM_SITE DS
            ON DS.SITE_ID = DB.SITE_ID
           AND DS.ACTIVE_FLAG = 'YES'
        WHERE BCL.CLEANING_COMPLETED_ON IS NOT NULL
          AND (BCL.CREATED_DATE > LOAD_DATE
               OR NVL(BCL.UPDATED_DATE, BCL.CREATED_DATE) > LOAD_DATE)
        GROUP BY
            D.DATE_KEY,
            DB.BIN_KEY,
            DCT.CLEANING_KEY,
            DS.SITE_KEY
    ) SRC
    ON (
        NVL(TGT.DATE_KEY, -1) = NVL(SRC.DATE_KEY, -1)
        AND NVL(TGT.BIN_KEY, -1) = NVL(SRC.BIN_KEY, -1)
        AND NVL(TGT.CLEANING_KEY, -1) = NVL(SRC.CLEANING_KEY, -1)
        AND NVL(TGT.SITE_KEY, -1) = NVL(SRC.SITE_KEY, -1)
    )
    WHEN MATCHED THEN
        UPDATE SET
            TGT.DAYS_SINCE_LAST_CLEANING = SRC.DAYS_SINCE_LAST_CLEANING,
            TGT.CLEAN_STANDARD_FREQ = SRC.CLEAN_STANDARD_FREQ
    WHEN NOT MATCHED THEN
        INSERT (
            DATE_KEY, BIN_KEY, CLEANING_KEY, SITE_KEY,
            DAYS_SINCE_LAST_CLEANING, CLEAN_STANDARD_FREQ
        )
        VALUES (
            SRC.DATE_KEY, SRC.BIN_KEY, SRC.CLEANING_KEY, SRC.SITE_KEY,
            SRC.DAYS_SINCE_LAST_CLEANING, SRC.CLEAN_STANDARD_FREQ
        );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

------------------------------------------------------------------------------
-- ORCHESTRATION WRAPPERS (1)
------------------------------------------------------------------------------

-- RUN_INCREMENTAL_OLAP_LOAD
CREATE OR REPLACE EDITIONABLE PROCEDURE "RUN_INCREMENTAL_OLAP_LOAD" (
    P_LOAD_DATE IN DATE DEFAULT NULL
) AS
    -- Orchestrates the full incremental OLAP refresh.
    --
    -- Every dimension loads before any fact: a fact row resolves its foreign
    -- keys by looking the business key up in the dimension, so a fact loaded
    -- against a stale dimension would miss the lookup and drop or misassign
    -- the row.
    --
    -- P_LOAD_DATE overrides the watermark; when NULL the last successful
    -- watermark is read from ETL_LOAD_CONTROL.
    --
    -- Note on atomicity: each INC_LOAD_* procedure commits its own work, so a
    -- mid-run failure leaves earlier steps committed. That is safe here because
    -- every step is a MERGE keyed on the business key, and the watermark is
    -- only advanced on full success -- so a re-run reprocesses the same window
    -- and converges. Do not advance LAST_LOAD_DATE in the exception handler.
    C_PROCESS         CONSTANT VARCHAR2(100) := 'OLAP_INCREMENTAL_LOAD';
    C_FIRST_LOAD      CONSTANT DATE          := DATE '1900-01-01';
    V_LAST_LOAD_DATE  DATE;
    V_LOAD_START_DATE DATE := SYSDATE;
BEGIN
    IF P_LOAD_DATE IS NOT NULL THEN
        V_LAST_LOAD_DATE := P_LOAD_DATE;
    ELSE
        BEGIN
            SELECT LAST_LOAD_DATE
              INTO V_LAST_LOAD_DATE
              FROM ETL_LOAD_CONTROL
             WHERE PROCESS_NAME = C_PROCESS;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                V_LAST_LOAD_DATE := NULL;   -- first ever run
        END;
    END IF;

    V_LAST_LOAD_DATE := NVL(V_LAST_LOAD_DATE, C_FIRST_LOAD);

    ---------------------------------------------------------------- dimensions
    INC_LOAD_DIM_DATE(V_LAST_LOAD_DATE);
    INC_LOAD_DIM_SITE(V_LAST_LOAD_DATE);
    INC_LOAD_DIM_PRODUCT(V_LAST_LOAD_DATE);
    INC_LOAD_DIM_CUSTOMER(V_LAST_LOAD_DATE);
    INC_LOAD_DIM_SHIPTO(V_LAST_LOAD_DATE);
    INC_LOAD_DIM_CARRIER(V_LAST_LOAD_DATE);
    INC_LOAD_DIM_PACKLINE(V_LAST_LOAD_DATE);
    INC_LOAD_DIM_MAINTENANCE_TYPE(V_LAST_LOAD_DATE);
    INC_LOAD_DIM_BIN(V_LAST_LOAD_DATE);
    INC_LOAD_DIM_CLEANING_TYPE(V_LAST_LOAD_DATE);
    INC_LOAD_DIM_PRODUCTION_MIX(V_LAST_LOAD_DATE);

    --------------------------------------------------------------------- facts
    INC_LOAD_FACT_SALES(V_LAST_LOAD_DATE);
    INC_LOAD_FACT_PACK_PRODUCTION(V_LAST_LOAD_DATE);
    INC_LOAD_FACT_MILL_PRODUCTION(V_LAST_LOAD_DATE);
    INC_LOAD_FACT_MAINTENANCE(V_LAST_LOAD_DATE);
    INC_LOAD_FACT_BIN_CLEANING(V_LAST_LOAD_DATE);

    -- MERGE, not UPDATE: a missing control row would otherwise silently update
    -- zero rows and leave the watermark unset, reprocessing everything forever.
    MERGE INTO ETL_LOAD_CONTROL tgt
    USING (SELECT C_PROCESS AS PROCESS_NAME FROM DUAL) src
       ON (tgt.PROCESS_NAME = src.PROCESS_NAME)
    WHEN MATCHED THEN
        UPDATE SET tgt.LAST_LOAD_DATE    = V_LOAD_START_DATE,
                   tgt.LAST_SUCCESS_DATE = SYSDATE,
                   tgt.STATUS            = 'SUCCESS'
    WHEN NOT MATCHED THEN
        INSERT (PROCESS_NAME, LAST_LOAD_DATE, LAST_SUCCESS_DATE, STATUS)
        VALUES (C_PROCESS, V_LOAD_START_DATE, SYSDATE, 'SUCCESS');

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;

        UPDATE ETL_LOAD_CONTROL
           SET STATUS = 'FAILED'
         WHERE PROCESS_NAME = C_PROCESS;

        COMMIT;
        RAISE;
END;
/
